### ISSUE TITLE
Custom Faction, Group composition issue.

### ISSUE THREAD

**Issue by Kissingya** [56curious/VKN_Official_Mod#3]
**Describe the bug**
Factions Independent: Modern China and Legion. Single model work fine as Independent. Groups show as Opfor and do not spawn.

I do assume it might be a side error in the Faction File. However I do not know which side means what neither where to modify it.

Spawned unit faction work as intended though.

[Legion.txt](https://github.com/56curious/VKN_Official_Mod/files/5035451/Legion.txt)
[Chinese Forces.txt](https://github.com/56curious/VKN_Official_Mod/files/5035453/Chinese.Forces.txt)

**Comment by Shagger-dev** [comment]
Could you please follow the template in order to help us Identify the actual problem here.
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
