### ISSUE TITLE
Finished Custom Faction: Blue Sky PMC

### ISSUE THREAD

**Issue by Kissingya** [56curious/VKN_Official_Mod#7]
Using base game NATO as a Faction Base. Gray / Blue themed PMC with mostly Infantry / Motorised assets.
[Blue Sky PMC.txt](https://github.com/56curious/VKN_Official_Mod/files/5035507/Blue.Sky.PMC.txt)

**Comment by Shagger-dev** [comment]
Could you please follow the template in order to help us Identify the actual problem here.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
